Spring: 
  application:
    name: hongguan-data
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hongguan?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    


mybatis: 
  type-aliases-package: com.hg.data.entity
server:
  port: 9006

  


